# Alcohol

Traditionally, the Finnish homicide scene has been heavily connected to drinking group violence among marginalised and unemployed males. The dynamics of homicide has been connected to total alcohol consumption in the long historical perspective (Lehti & Sirén 2020). However, while alcohol retains its high prevalence in crimes of violence, its role is decreasing. Both SOCM and youth crime surveys (Näsi 2016, 15–16) indicate that the proportion of offences committed while drunk has been decreasing during the recent decades. In homicide, the prevalence of alcohol has de-creased considerably since the 1990s (Lehti, 2014). Simultaneously with the decreasing role of alcohol, the share of homicides investigated as murders (instead of manslaughter or other penal codes for homicide) increased. During the last decade, the proportion of alcohol-related offend-ers has been stable. Most Finnish homicides are still related to alcohol and are investigated as manslaughter. Alcohol has been replaced in part by drugs and psychoactive substances as incident-level correlates of crime.
